.\"
.\" Copyright (c) 2009 Vitaly Sinilin <vs@kp4.ru>
.\"
.TH id321 1 "6 March 2010" id321
.SH NAME
id321 \- ID3 tags manipulation tool
.SH SYNOPSIS
.B id321
[pr[int]] [-1|-2] [-v] [-eENCODING] [-f FORMAT|-F FRAME] FILE...
.br
.B id321
mo[dify] [-1|-2] [-v] KEY=value FILE...
.br
.B id321
cp|copy [-1|-2] [-v] SOURCE DEST
.br
.B id321
sy[nc] [-1|-2] [-v] FILE...
.br
.B id321
rm|delete [-1|-2] [-v] [-E] FILE...
.br
.SH DESCRIPTION
.B id321
is a program to read and write ID3 tags. The following versions of ID3 tags
are supported: 1.0, 1.1, 1.2, 1.3, enhanced v1 tag, 2.2, 2.3, 2.4.
.br
.SH ACTIONS
.TP
.B pr | print
Print tags. This is the default action. Without
.BR -f " or " -F
option whole tags of specified version will be dumped as a list of
frames/fields with their text values.
.TP
.B mo | modify
Modify tags.
.TP
.B cp | copy
Copy tags from SOURCE to DEST.
.TP
.B sy | sync
Synchronize v1 and v2 tags values.
.TP
.B rm | delete
Delete tags.
.br
.SH OPTIONS
.TP
.BI -1 "[1|2|3|e]
Perform the action on v1 tags only. If the minor version is not specified,
the scope of the action is any v1 tag.
.TP
.BI -2 "[2|3|4]
Perform the action on v2 tags only. If the minor version is not specified,
the scope of the action is any v2 tag.
.TP
.BI -E
Expert mode. Some dangerous actions are allowed in this mode.
.TP
.BI -e "ENCODING
Force tag's data encoding. If
.I ENCODING
is omitted, it will be taken from the
current locale. This option does not affect output of
.B -F
option. Note, with
.B modify
action this option results in non-standard tags.
.TP
.BI -f " FORMAT
Print tags using printf-like format string. Only useful with
.B print
action.
.TP
.BI -F " FRAME|a|c|g|G|l|n|t|y
Dump specified tag's frame/field as a binary data. This option has
a little sense for v1 tags, but it still can be used to retrieve
raw tag's field value regardless current locale. Only useful with
.B print
action.
.TP
.B -v
Be verbose.
.SH EXAMPLES
Dump all ID3 tags:
.IP
.B id321 best.mp3
.LP
Dump any ID3v1 tag (enhanced, v1.3, v1.2, v1.1, v1.0):
.IP
.B id321 -1 best.mp3
.LP
Dump enhanced ID3v1 tag only (if there is a regular ID3v1 tag only,
nothing will be dumped):
.IP
.B id321 -1e best.mp3
.LP
Print tags as a formatted string. As only one value for each field can
be printed ID3v2 tag has higher priority when tag version is not
specified and alias used. For ID3v2 tags you can specify the frame id
(e.g. %TIT2 for song title).
.IP
.B id321 -f """%n - %t""" best.mp3
.LP
Dump frame in binary format:
.IP
.B id321 -F TIT2
.LP
Synchronize ID3v1 tag data with ID3v2 tag data. Original data will be
lost even if there is no corresponding frame in ID3v2 tag. If minor
version is specified and existent tag has another minor version, it
will be converted to the specified one, otherwise existent minor
version will be preserved. If the file has no ID3v1 tag, it will be
created having the specified minor version or ID3v1.3 by default.
.IP
.B id321 sync -1 best.mp3
.LP
Synchronize ID3v2 tag data with ID3v1 tag data. The same as above.
ID3v2.4 is default for ID3v2.
.IP
.B id321 sync -2 best.mp3
.LP
Delete all ID3 tags:
.IP
.B id321 rm best.mp3
.LP
Delete any ID3v1 tag:
.IP
.B id321 rm -1 best.mp3
.LP
Delete ID3v1 enhanced tag. Notice that ID3v1 enhanced tag is considered
as including ID3v1 tag, so general ID3v1 tag will be removed as well.
In order to remove only enhanced part use `modify -11' command instead.
.IP
.B id321 rm -1e best.mp3
.LP
Modify tag. If no version is specified and there are both v1 and v2 tags
in the file, both v1 and v2 tags will be modified. If there is no tags
in the file and no version is specified an ID3v2.4 tag will be prepended
at the very begining of the file. If version is specified the only tag
of this version will be modified. Moreover, if also minor version is
specified existent tag will be converted to this minor version.
.IP
.B id321 modify -t Title -a Artist -n 1 -c Comment -y 2009 best.mp3
.br
.B id321 modify -24 -F TIT2=Title -F TPE1=Artist best.mp3
.LP
Convert tag minor version.
.IP
.B id321 modify -11 best.mp3
.LP
Padding size of ID3v2 tag.

If value has plus sign at the very begining it is relative value,
i.e. the tag size will be minimal size needed to store all tag's data
plus the specified value. Otherwise it is absolute value, i.e. the
maximum size the tag can be. If it is insufficient to store all tag's
data error message will be printed.
.SH AUTHOR
Written by Vitaly Sinilin <vs@kp4.ru>
