.\"
.\" Copyright (c) 2009\-2011 Vitaly Sinilin <vs@kp4.ru>
.\"
.TH id321 1 "26 December 2011" id321
.SH NAME
id321 \- ID3 tags manipulation tool
.SH SYNOPSIS
.B id321
.RB [ pr [ int ]]
.RI [ OPTION... ]
[\fB\-f \fIFORMAT\fR|\fB\-F \fIFRAME\fR]
.IR FILE ...
.br
.B id321
.BR mo [ dify ]
[\fIOPTION\fR...] \fIFILE\fR...
.br
.B id321
.RB { cp | copy }
[\fIOPTION\fR...] \fISOURCE DEST
.br
.B id321
.BR sy [ nc ]
{\fB\-1\fR|\fB\-2\fR} [\fIOPTION\fR...] \fIFILE\fR...
.br
.B id321
.RB { rm | delete }
[\fIOPTION\fR...] \fIFILE\fR...
.br
.SH DESCRIPTION
.B id321
is a program to read and write ID3 tags. The following versions of ID3 tags
are supported: 1.0, 1.1, 1.2, 1.3, enhanced tag, 2.2, 2.3, 2.4.
.br
.SH ACTIONS
.TP
.BR pr " | " print
Print tags. This is the default action. Without
.BR \-f " or " \-F
option whole tags of specified version will be dumped as a list of
frames/fields with their text values.
.TP
.BR mo " | " modify
Modify tags.
.TP
.BR cp " | " copy
Copy tags from
.I SOURCE
to
.IR DEST .
Original tags of matching version in
.I DEST
will be silently overwritten. If
.I DEST
has a tag of version which is absent in
.IR SOURCE ,
it will be preserved.
.TP
.BR sy " | " sync
Synchronise v1 and v2 tags values. A target version shall be specified.
Empty values in a source tag do not replace conforming values in a target tag.
If you do not need values from the target tag, remove it beforehand using
.B rm
action.
.TP
.BR rm " | " delete
Delete tags.
.br
.SH COMMON OPTIONS
.TP
.BI \-1 "[1|2|3|e]
Perform the action on v1 tags only. The optional parameter is a minor version.
If the minor version is not specified, the scope of the action is any v1 tag.
.TP
.BI \-2 "[2|3|4]
Perform the action on v2 tags only. The optional parameter is a minor version.
If the minor version is not specified, the scope of the action is any v2 tag.
.TP
.BI \-E
Expert mode. Some dangerous actions are allowed in this mode.
.TP
.BI \-e "ENCODING
.RS
Force tag's data encoding.
.RI The " ENCODING
is a colon\-separated list of codesets with the following order:
.RS 7

.B V1ENC:ISO\-8859\-1:UCS\-2:UTF\-16:UTF\-16BE:UTF\-8

.RE
It defines an encoding mapping for v1 (V1ENC), v2.2 and v2.3 (ISO\-8859\-1,
UCS\-2), and v2.4 (ISO\-8859\-1, UTF\-16, UTF\-16BE, UTF\-8) tags.
If an element of the list is an empty string, the default codeset value will be
used (the default codeset for V1ENC is ISO\-8859\-1).
An incomplete list may be specified. If the incomplete list has a trailing
colon, its last specified element value will be propagated to all subsequent
omitted elements. Otherwise, omitted elements will have their default values.
If whole
.I ENCODING
is omitted, V1ENC and ISO\-8859\-1 values will be taken from the
current locale codeset. This option does not affect output of
.B \-F
option. Note, with
.BR modify " or " sync
action this option leads to non\-standard tags.
.br
.I ENCODING
can be also specified via the environment variable \fBID321_ENCODING\fR,
but the command\-line option takes precedence.
.RE
.TP
.B \-v
Be verbose.
.SH PRINT OPTIONS
.TP
.BI \-f " FORMAT
Print tags using printf\-like format string.
.TP
.BI \-F " FRAME
Dump specified ID3v2 tag's frame as a binary data.
.SH MODIFY OPTIONS
For the following options, an empty string as the option argument will
cause deletion of a corresponding ID3v2 frame.
.TP
\fB\-t\fR, \fB\-\-title \fITITLE
.TP
\fB\-a\fR, \fB\-\-artist \fIARTIST
.TP
\fB\-l\fR, \fB\-\-album \fIALBUM
.TP
\fB\-g\fR, \fB\-\-genre \fR{\fIGENRE_ID\fR[\fB:\fIGENRE_STRING\fR]|\fB:\fIGENRE_STRING\fR}
.TP
\fB\-y\fR, \fB\-\-year \fIYEAR
.TP
\fB\-c\fR, \fB\-\-comment \fR[[\fILANG\fB:\fR]\fIDESC\fB:\fR]\fICOMMENT
.IR LANG " and " DESC
can have a special value '*' to match all comment frames regardless their
language and description respectively. In this case all matching frames
will be altered if \fICOMMENT\fR is not empty, or deleted if it is.
Colons (\fB:\fR) and asterisks (\fB*\fR) within
.IR LANG ", " DESC " and " COMMENT
should be escaped with '\\' not to have their special
meanings.
If omitted, the default language is XXX and the default description is an
empty string.
.P
The following options are ID3v2.x specific. There is no sense using them
with other versions of tags.
.TP
\fB\-F\fR, \fB\-\-frame \fIFRAME_ID\fR[\fB[\fR{\fIINDEX\fR|\fB*\fR}\fB]\fR][[\fB:\fR{\fIENCODING\fR|\fBbin\fR}]\fB:\fR{\fB\-\fR|\fIDATA\fR}]
Modify/delete arbitrary ID3v2 frame. A new value can be taken from stdin
using '\fB\-\fR' instead of \fIDATA\fR. To use a single dash as a new value
escape it with a backslash as '\fB\\\-\fR'.
If only \fIFRAME_ID\fR is specified, the frame will be deleted.
If no \fIINDEX\fR is specified, a first matching frame will be affected.
If the special index value '\fB*\fR' is specified, all matching frames will be
affected. If empty index is specified (i.e. empty brackets as '\fBTIT2[]\fR')
a new frame will be created regardless whether \fIDATA\fR is specified or not.
If no \fIENCODING\fR is specified, a default encoding will be used. If the
special encoding value \fBbin\fR is specified, the data will be placed into
the frame as is.
Note that the acceptable \fIENCODING\fR values depend on the tag version
and the encoding mapping (see \fB\-e\fR option for details). No validation is
performed for this option, so use it only if you are sure what you are doing.
.P
The following options are enhaced tag specific. There is no sense using them
with other versions of tags.
.TP
\fB\-t\fR, \fB\-\-speed \fR{\fBslow\fR|\fBmedium\fR|\fBfast\fR|\fBhardcore\fR}
.TP
\fB\-\-start\-time \fIMMM:SS
.TP
\fB\-\-end\-time \fIMMM:SS
.SH WRITE OPTIONS
The following options are applicable for all actions which write tags,
namely
.BR modify ", " sync " and " copy .
.TP
.B \-\-no\-unsync
Do not unsynchronise v2 tags when writing. By default, v2 tags are being
unsynchronised.
.TP
\fB\-s\fR, \fB\-\-size \fISIZE
A preferable size of v2 tag to be written. If the specified size is not enough
to store whole tag, it will be ignored and whole tag will be written.
.SH EXAMPLES
Dump all ID3 tags:
.IP
.B id321 best.mp3
.LP
Dump any ID3v1 tag (enhanced, v1.3, v1.2, v1.1, v1.0):
.IP
.B id321 \-1 best.mp3
.LP
Dump an enhanced ID3v1 tag only (if there is a regular ID3v1 tag only,
nothing will be dumped):
.IP
.B id321 \-1e best.mp3
.LP
Print tags as a formatted string. As only one value for each field can
be printed the ID3v2 tag has higher priority when a tag version is not
specified and an alias used. For ID3v2 tags you can specify the frame id
(e.g. %TIT2 for song title).
.IP
.B id321 \-f """%n \- %t""" best.mp3
.LP
Note that the frame name depends on the tag minor version. If you are not sure
about exact minor version of the tag, use aliases instead.

Dump the frame TIT2 in a binary format:
.IP
.B id321 \-F TIT2
.LP
Synchronise ID3v1 tag data with ID3v2 tag data. If a minor
version is specified and the existent tag has another minor version, it
will be converted to the specified one, otherwise the existent minor
version will be preserved. If the file has no ID3v1 tag, it will be
created having the specified minor version or 3 by default.
.IP
.B id321 sync \-1 best.mp3
.LP
Synchronise ID3v2 tag data with ID3v1 tag data. The same as above.
4 is the default minor version for ID3v2.
.IP
.B id321 sync \-2 best.mp3
.LP
Delete all ID3 tags:
.IP
.B id321 rm best.mp3
.LP
Delete any ID3v1 tag:
.IP
.B id321 rm \-1 best.mp3
.LP
Delete an enhanced tag. Notice that the enhanced tag is considered
as including the ID3v1 tag, so general ID3v1 tag will be removed as well.
In order to remove the enhanced part only use
.B modify \-11
command instead.
.IP
.B id321 rm \-1e best.mp3
.LP
Modify tag. If no version is specified and there are both v1 and v2 tags
in the file, both v1 and v2 tags will be modified. If there is no tags
in the file and no version is specified an ID3v2.4 tag will be prepended
at the very begining of the file. If a version is specified the only tag
of this version will be modified. Moreover, if also a minor version is
specified, the existent tag will be converted in order to have the specified
minor version.
.IP
.B id321 modify \-t Title \-a Artist \-n 1 \-c Comment \-y 2009 best.mp3
.LP
In order to delete ID3v2 frame assign it an empty string. The following
example will delete a title frame and all English comment frames.
.IP
.B id321 modify \-t '' \-c 'eng:*:' best.mp3
.LP
Convert tag minor version.
.IP
.B id321 modify \-11 best.mp3
.LP
.SH BUGS
Conversion between minor versions of ID3v2 tags is not implemented yet.
.SH AUTHOR
Written by Vitaly Sinilin <vs@kp4.ru>
.LP
.SH SEE ALSO
ID3v1 tag specification:
.IP
http://mpgedit.org/mpgedit/mpeg_format/mpeghdr.htm#MPEGTAG
.LP
ID3v1.2 tag informal standard:
.IP
http://www.birdcagesoft.com/ID3v12.txt
.LP
ID3v1.3 tag informal standard:
.IP
http://lib313.sourceforge.net/id3v13.html
.LP
Enhanced tag specification:
.IP
http://www.fortunecity.com/underworld/sonic/3/id3tag.html
.LP
ID3v2.2 tag informal standard:
.IP
http://www.id3.org/id3v2\-00
.LP
ID3v2.3 tag informal standard:
.IP
http://www.id3.org/d3v2.3.0
.LP
ID3v2.4 tag informal standard:
.IP
http://www.id3.org/id3v2.4.0\-structure
.br
http://www.id3.org/id3v2.4.0\-frames
.LP
